---
# EPEL YUM repo URL
clamav_epel_yumrepo_url: "{{ yumrepo_epel_url | default('https://dl.fedoraproject.org/pub/epel/$releasever/$basearch/') }}"

# EPEL YUM repo GPG key
clamav_epel_yumrepo_gpgkey: "{{ yumrepo_epel_gpgkey | default('https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-$releasever') }}"

# Additional EPEL YUM repo params
clamav_epel_yumrepo_params: "{{ yumrepo_epel_params | default({}) }}"

- name: Ensure Freshclam service is available.
  template:
    src: clamd-freshclam.service.j2
    dest: /lib/systemd/system/clamd-freshclam.service
    mode: 0644
  register: freshclam_service_template

- name: Reload systemd after adding service.
  systemd:
    state: stopped
    daemon_reload: yes
    name: "{{ clamav_freshclam_daemon }}"
  when: freshclam_service_template.changed
